version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - tomaszwaszczyk
  assignees:
  - tomaszwaszczyk
  ignore:
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.11.2
    - 2.13.4
  - dependency-name: framer-motion
    versions:
    - 3.1.1
    - 3.2.1
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 2.10.0
    - 2.8.0
  - dependency-name: gatsby-plugin-catch-links
    versions:
    - 2.7.0
    - 2.9.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.8.1
  - dependency-name: lodash
    versions:
    - 4.17.20
